export const RESPONSE_CODE_SUCCESS = 200;
export const RESPONSE_CODE_CREATED = 201;
export const RESPONSE_CODE_UNAUTHORIZED = 401;
export const RESPONSE_CODE_NOT_FOUND = 404;
export const RESPONSE_CODE_UNPRONOUNCEABLE_ENTITY = 422;
